### ISSUE TITLE
Add testing/staging output buckets

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/OpenScPCA-nf#44]
Currently we have only the "production" output buckets specified in the Nextflow workflow, but this is probably not the ideal way to have the defaults set up, as any errors in the workflow could result in corrupted data in the buckets used by other tools/the `scpca-analysis` scripts and modules .

We should probably change the defaults to some kind of staging location, and copy the results over in a separate step, or with a rerun and the final output bucket specified.  This may take making a few more buckets for these purposes.

**Comment by jashapiro** [comment]
@jaclyn-taroni, now that you are back, I wanted to alert you to this issue. In short, I think it would be a good idea to have some staging buckets to mirror `openscpca-nf-workflow-results`, `openscpca-test-data-release-public-access` and `openscpca-test-workflow-results-public-access` for output from OpenScPCA-nf. The latter two would not need to have public access (unlike the final versions), as they would only be used for workflow tests. 

If you agree this is a good idea, I assume we would want to create an issue in https://github.com/AlexsLemonade/OpenScPCA-infra to handle creating those buckets?

**Comment by jaclyn-taroni** [comment]
Yes, this makes sense to me. I would expect a ticket in `OpenScPCA-infra` for creating a bucket with public access blocked with the same permissions for the Nextflow, etc. We can discuss over there what account we think it belongs in.
