### ISSUE TITLE
Detect doublets with workflow

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenScPCA-nf#69]
This issue tracks running the workflow to detect doublets across ScPCA data and generate associated results. More details to come!

**Comment by sjspielman** [comment]
I had originally assigned myself here, but given permissions, this should probably go to @jashapiro instead. (unless I should just launch the workflow from https://github.com/AlexsLemonade/OpenScPCA-nf/actions/workflows/run-batch.yml?)

**Comment by jashapiro** [comment]
You should be able to launch the workflow from https://github.com/AlexsLemonade/OpenScPCA-nf/actions/workflows/run-batch.yml

Run first with `full` and `staging` so we can make sure the results are as expected, then follow with `full` and `prod`.

I tried to give you access to the [Seqera cloud workspace](https://cloud.seqera.io/orgs/CCDL/workspaces/OpenScPCA/watch) to monitor the run; let me know if you were able to access that.

**Comment by jaclyn-taroni** [comment]
I think the question is whether or not we want to do a semantically versioned release to accomplish this task?

@sjspielman - your permissions do not materially differ from Josh's for this task unless something fails in a specific set of ways.

**Comment by jashapiro** [comment]
> I think the question is whether or not we want to do a semantically versioned release to accomplish this task?

I think we do want to get to this, maybe for the `prod` run, but there are a few steps before we get there: In particular, #73 is blocking  a semantic release, but that is blocked by https://github.com/AlexsLemonade/OpenScPCA-analysis/issues/623  (for which I also want to do #74). I was hoping to tackle #74  and https://github.com/AlexsLemonade/OpenScPCA-analysis/issues/623 today.

**Comment by jaclyn-taroni** [comment]
Yes, I expected there were some blockers. I've now set them as blockers. @sjspielman, I would do the staging stuff now as @jashapiro describes in https://github.com/AlexsLemonade/OpenScPCA-nf/issues/69#issuecomment-2245289871, but consider this closed when we run a `prod` run by tagging a semvar release.

**Comment by sjspielman** [comment]
> Run first with `full` and `staging` so we can make sure the results are as expected

Results for both `merge_sce` and `detect_doublets` look as expected here!

**Comment by jashapiro** [comment]
With [v0.1.0 created](https://github.com/AlexsLemonade/OpenScPCA-nf/releases/tag/v0.1.0), the prod run of this module has been triggered. See https://cloud.seqera.io/orgs/CCDL/workspaces/OpenScPCA/watch for current progress!

**Comment by jashapiro** [comment]
The run failed, but the failure seemed to be related to an error pulling the docker image, which I would expect to be transient. The docker image was pulled successfully many times before! 

Nonetheless, rather than retriggering the run directly, I think we may as well cut a point release which incorporates the change in #82, so I will take that approach.

**Comment by jashapiro** [comment]
The run https://cloud.seqera.io/orgs/CCDL/workspaces/OpenScPCA/watch/VcxEXOaURslUi  seems to be on track to finish; it is only working on the merges now and all doublet_detection is done.

**Comment by sjspielman** [comment]
> The run https://cloud.seqera.io/orgs/CCDL/workspaces/OpenScPCA/watch/VcxEXOaURslUi seems to be on track to finish; it is only working on the merges now and all doublet_detection is done.

🤞

**Comment by sjspielman** [comment]
Merging successfully wrapped up 🚀 https://cloud.seqera.io/orgs/CCDL/workspaces/OpenScPCA/watch/VcxEXOaURslUi
The workflow is now exporting the last project to anndata which I expect to take a few hours.

**Comment by sjspielman** [comment]
The run completed successfully, and doublets are now available in the results release! I was able to download them successfully with `./download-results.py --modules doublet-detection` 🎉🎉🎉 

@Jen-OMalley we might want to make an announcement about it?

**Comment by sjspielman** [comment]
> we might want to make an announcement about it?

We're discussing an announcement about this on Slack, so this issue can now be closed.
